from enum import Enum


class QuotationStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_MANAGER_APPROVAL = "PENDING_MANAGER_APPROVAL"
    PENDING_FINANCE_APPROVAL = "PENDING_FINANCE_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    RETURNED_FOR_REVISION = "RETURNED_FOR_REVISION"
    CANCELLED = "CANCELLED"


class RiskLevel(str, Enum):
    GREEN = "GREEN"
    YELLOW = "YELLOW"
    CORAL_RED = "CORAL_RED"


class QuoteLineSource(str, Enum):
    MANUAL = "MANUAL"
    UPSELL = "UPSELL"


class RiskReasonCode(str, Enum):
    WITHIN_STANDARD_DISCOUNT = "WITHIN_STANDARD_DISCOUNT"
    ABOVE_STANDARD_WITHIN_MAX = "ABOVE_STANDARD_WITHIN_MAX"
    DISCOUNT_ABOVE_MAX = "DISCOUNT_ABOVE_MAX"
    NO_APPLICABLE_DISCOUNT_POLICY = "NO_APPLICABLE_DISCOUNT_POLICY"
    NEGATIVE_MARGIN = "NEGATIVE_MARGIN"
    ZERO_REVENUE_WITH_COST = "ZERO_REVENUE_WITH_COST"


class AuditEventType(str, Enum):
    QUOTE_CREATED = "QUOTE_CREATED"
    QUOTE_UPDATED = "QUOTE_UPDATED"
    LINE_ADDED = "LINE_ADDED"
    LINE_UPDATED = "LINE_UPDATED"
    LINE_REMOVED = "LINE_REMOVED"
    QUOTE_RECALCULATED = "QUOTE_RECALCULATED"
    QUOTE_CANCELLED = "QUOTE_CANCELLED"
