from enum import Enum
from app.core.roles import RoleName


class QuotationStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_MANAGER_APPROVAL = "PENDING_MANAGER_APPROVAL"
    PENDING_FINANCE_APPROVAL = "PENDING_FINANCE_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    RETURNED_FOR_REVISION = "RETURNED_FOR_REVISION"
    CANCELLED = "CANCELLED"
    SENT_TO_CUSTOMER = "SENT_TO_CUSTOMER"
    UNDER_NEGOTIATION = "UNDER_NEGOTIATION"
    UNDER_CUSTOMER_REVIEW = "UNDER_CUSTOMER_REVIEW"
    REAPPROVAL_REQUIRED = "REAPPROVAL_REQUIRED"
    CUSTOMER_ACCEPTED = "CUSTOMER_ACCEPTED"
    CUSTOMER_CONFIRMED = "CUSTOMER_CONFIRMED"
    EXPIRED = "EXPIRED"


class RiskLevel(str, Enum):
    GREEN = "GREEN"
    YELLOW = "YELLOW"
    CORAL_RED = "CORAL_RED"


class QuoteLineSource(str, Enum):
    MANUAL = "MANUAL"
    UPSELL = "UPSELL"


class RiskReasonCode(str, Enum):
    WITHIN_STANDARD_DISCOUNT = "WITHIN_STANDARD_DISCOUNT"
    ABOVE_STANDARD_WITHIN_MAX = "ABOVE_STANDARD_WITHIN_MAX"
    DISCOUNT_ABOVE_MAX = "DISCOUNT_ABOVE_MAX"
    NO_APPLICABLE_DISCOUNT_POLICY = "NO_APPLICABLE_DISCOUNT_POLICY"
    NEGATIVE_MARGIN = "NEGATIVE_MARGIN"
    ZERO_REVENUE_WITH_COST = "ZERO_REVENUE_WITH_COST"


class AuditEventType(str, Enum):
    QUOTE_CREATED = "QUOTE_CREATED"
    QUOTE_UPDATED = "QUOTE_UPDATED"
    LINE_ADDED = "LINE_ADDED"
    LINE_UPDATED = "LINE_UPDATED"
    LINE_REMOVED = "LINE_REMOVED"
    QUOTE_RECALCULATED = "QUOTE_RECALCULATED"
    QUOTE_CANCELLED = "QUOTE_CANCELLED"
    QUOTE_SENT_TO_CUSTOMER = "QUOTE_SENT_TO_CUSTOMER"
    QUOTE_VERSION_CREATED = "QUOTE_VERSION_CREATED"
    NEGOTIATION_STARTED = "NEGOTIATION_STARTED"
    CUSTOMER_COMMENT_ADDED = "CUSTOMER_COMMENT_ADDED"
    CUSTOMER_CHANGE_REQUESTED = "CUSTOMER_CHANGE_REQUESTED"
    CUSTOMER_COUNTER_OFFERED = "CUSTOMER_COUNTER_OFFERED"
    NEGOTIATION_REQUEST_ACCEPTED = "NEGOTIATION_REQUEST_ACCEPTED"
    NEGOTIATION_REQUEST_REJECTED = "NEGOTIATION_REQUEST_REJECTED"
    CUSTOMER_REQUEST_WITHDRAWN = "CUSTOMER_REQUEST_WITHDRAWN"
    NEGOTIATION_TERMS_APPLIED = "NEGOTIATION_TERMS_APPLIED"
    REAPPROVAL_REQUIRED = "REAPPROVAL_REQUIRED"
    NEGOTIATION_APPROVAL_STARTED = "NEGOTIATION_APPROVAL_STARTED"
    NEGOTIATION_APPROVED = "NEGOTIATION_APPROVED"
    NEGOTIATION_REJECTED = "NEGOTIATION_REJECTED"
    QUOTE_RESENT = "QUOTE_RESENT"
    CUSTOMER_CONFIRMED = "CUSTOMER_CONFIRMED"


class NotificationType(str, Enum):
    QUOTE_SENT = "QUOTE_SENT"
    CUSTOMER_COMMENT = "CUSTOMER_COMMENT"
    CUSTOMER_COUNTER_OFFER = "CUSTOMER_COUNTER_OFFER"
    NEGOTIATION_ACCEPTED = "NEGOTIATION_ACCEPTED"
    NEGOTIATION_REJECTED = "NEGOTIATION_REJECTED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVAL_UPDATED = "APPROVAL_UPDATED"
    QUOTE_REAPPROVED = "QUOTE_REAPPROVED"
    QUOTE_CONFIRMED = "QUOTE_CONFIRMED"
    CUSTOMER_ACCEPTED = "CUSTOMER_ACCEPTED"


class VersionSourceType(str, Enum):
    INITIAL_SEND = "INITIAL_SEND"
    INITIAL_RELEASE = "INITIAL_RELEASE"
    INTERNAL_REVISION = "INTERNAL_REVISION"
    CUSTOMER_COUNTER_ACCEPTED = "CUSTOMER_COUNTER_ACCEPTED"
    REAPPROVED = "REAPPROVED"
    RESENT = "RESENT"


class NegotiationMessageType(str, Enum):
    COMMENT = "COMMENT"
    LINE_QUESTION = "LINE_QUESTION"
    INTERNAL_REPLY = "INTERNAL_REPLY"
    SYSTEM = "SYSTEM"


class NegotiationRequestType(str, Enum):
    CHANGE_REQUEST = "CHANGE_REQUEST"
    COUNTER_OFFER = "COUNTER_OFFER"


class NegotiationRequestStatus(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"
    SUPERSEDED = "SUPERSEDED"
